const V='porfirchik-arbiter-v1.0.0-20261002',GID=228330620,EV_LEASE=240000,JOB_LEASE=720000,DWELL=120000,TTL=604800000;
const E=new TextEncoder();
const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const T=(x,s=200)=>new Response(String(x),{status:s,headers:{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'}});
const H=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const SHA=async s=>H(await crypto.subtle.digest('SHA-256',E.encode(String(s))));
async function HM(sec,s){let k=await crypto.subtle.importKey('raw',E.encode(sec),{name:'HMAC',hash:'SHA-256'},false,['sign']);return H(await crypto.subtle.sign('HMAC',k,E.encode(s)))}
const CP=async t=>'/vk/callback/'+(await SHA('nd-vk-path:'+t)).slice(0,32);
const RID=k=>{let h=2166136261;for(let i=0;i<k.length;i++){h^=k.charCodeAt(i);h=Math.imul(h,16777619)}h=(h>>>0)&0x7fffffff;return h||1};
const ERR=e=>String(e&&e.message||e||'error').slice(0,500);
async function SIG(tok,ts,owner,ep,event,lane,body){return HM(tok,['nd-porfirchik-arbiter-v1',ts,owner,ep,event,lane,await SHA(body)].join('\n'))}
async function AUTH(r,e,body){let ts=r.headers.get('x-nd-timestamp')||'',o=r.headers.get('x-nd-owner')||'',ep=r.headers.get('x-nd-epoch')||'',ev=r.headers.get('x-nd-event')||'',ln=r.headers.get('x-nd-lane')||'event',got=r.headers.get('x-nd-signature')||'',n=Number(ts);if(!got||!Number.isFinite(n)||Math.abs(Date.now()-n)>180000)return null;let ex=await SIG(e.VK_GROUP_TOKEN,ts,o,ep,ev,ln,body);if(ex.length!==got.length)return null;let d=0;for(let i=0;i<ex.length;i++)d|=ex.charCodeAt(i)^got.charCodeAt(i);return d?null:{owner:o,epoch:Number(ep),event:ev,lane:ln}}
async function VK(e,m,p){let b=new URLSearchParams(Object.assign({},p,{access_token:e.VK_GROUP_TOKEN,v:e.VK_API_VERSION||'5.199'})),r=await fetch('https://api.vk.com/method/'+m,{method:'POST',body:b});let x=await r.json();if(!r.ok||x.error)throw Error('VK '+m+': '+(x.error&&x.error.error_msg||r.status));return x.response}
async function KEY(b){if(b.event_id)return 'vk:'+(b.group_id||GID)+':'+b.event_id;let m=b.object&&b.object.message||b.object||{},s=[b.group_id||GID,m.peer_id||'',m.conversation_message_id||m.id||'',m.date||'',m.from_id||'',m.text||''].join('|');return 'vk:fallback:'+(await SHA(s)).slice(0,40)}
async function BF(e,ev,o,ep,ms){let base=o==='RENDER'?e.RENDER_BASE_URL:e.RAILWAY_BASE_URL,ts=String(Date.now()),body=ev.raw,sg=await SIG(e.VK_GROUP_TOKEN,ts,o,String(ep),ev.key,'event',body),c=new AbortController(),tm=setTimeout(()=>c.abort(),ms);try{return await fetch(base.replace(/\/+$/,'')+await CP(e.VK_GROUP_TOKEN),{method:'POST',body,signal:c.signal,headers:{'content-type':'application/json','x-nd-timestamp':ts,'x-nd-owner':o,'x-nd-epoch':String(ep),'x-nd-event':ev.key,'x-nd-lane':'event','x-nd-attempt':ev.key+':'+ev.attempts,'x-nd-arbiter-origin':ev.origin,'x-nd-signature':sg}})}finally{clearTimeout(tm)}}
export class PorfirchikArbiter{
 constructor(c,e){this.c=c;this.e=e;this.s=c.storage}
 async M(){let m=await this.s.get('m');if(!m){m={owner:'RAILWAY',epoch:1,ownerSince:Date.now(),minUntil:0,pf:0,pfSince:0,hs:0,hsSince:0,rf:0,ae:0,aj:0,fo:0,fb:0,lastSwitch:null,lastError:null};await this.s.put('m',m)}return m}
 async PM(m){await this.s.put('m',m)}
 async A(t=Date.now()+20){let a=await this.s.getAlarm();if(a==null||t<a)await this.s.setAlarm(t)}
 async fetch(r){let p=new URL(r.url).pathname,x=await r.json().catch(()=>({}));if(p==='/in')return this.ing(x);if(p==='/out')return this.out(x);if(p==='/done')return this.done(x);if(p==='/js')return this.js(x);if(p==='/jd')return this.jd(x);if(p==='/force')return this.force(x);if(p==='/diag')return J(await this.diag());return J({ok:false,error:'not_found'},404)}
 async ing(a){if(!a.key)return J({ok:false,error:'key'},400);let k='e:'+a.key,o=await this.s.get(k);if(o)return J({ok:true,duplicate:true,state:o.state,owner:o.owner,epoch:o.epoch});let n=Date.now(),ev={key:a.key,raw:String(a.raw||''),origin:String(a.origin||''),state:'RECEIVED',owner:null,epoch:null,attempts:0,next:n,lease:0,received:n,updated:n};await this.s.put(k,ev);await this.A(n+10);let m=await this.M();return J({ok:true,duplicate:false,owner:m.owner,epoch:m.epoch})}
 async out(a){let k=String(a.event_key||''),ok=String(a.output_key||''),peer=Number(a.peer_id||0),o=String(a.owner||''),ep=Number(a.epoch||0),m=await this.M(),ev=await this.s.get('e:'+k);if(!k||!ok||!peer||!ev)return J({ok:false,error:'bad_out'},400);if(m.owner!==o||m.epoch!==ep||ev.owner!==o||ev.epoch!==ep)return J({ok:false,error:'stale_fence',owner:m.owner,epoch:m.epoch},409);let sk='o:'+ok,r=await this.s.get(sk);if(r&&r.state==='SENT')return J({ok:true,deduped:true,vk_result:r.vk});let msg=String(a.message||'');if(!msg)return J({ok:false,error:'empty'},400);r=r||{key:ok,event:k,owner:o,epoch:ep,peer,random:RID(ok),state:'PENDING',tries:0,created:Date.now()};r.message=msg;r.tries++;r.updated=Date.now();await this.s.put(sk,r);try{if(this.e.QUALIFICATION_MODE==='1'&&k.startsWith('vk:'+GID+':nd-qual-')){r.vk='qualification-simulated';r.state='SENT';}else{r.vk=await VK(this.e,'messages.send',{peer_id:peer,random_id:r.random,message:msg});r.state='SENT';}r.sent=Date.now();r.error=null;await this.s.put(sk,r);return J({ok:true,deduped:false,vk_result:r.vk})}catch(z){r.error=ERR(z);r.next=Date.now()+Math.min(60000,2000*r.tries);await this.s.put(sk,r);await this.A(r.next);return J({ok:false,error:'vk_pending'},503)}}
 async done(a){let ev=await this.s.get('e:'+a.event_key);if(!ev)return J({ok:false,error:'unknown'},404);let m=await this.M();if(ev.owner!==a.owner||ev.epoch!==Number(a.epoch))return J({ok:false,error:'stale_completion'},409);if(ev.state!=='COMPLETED'&&(ev.state==='DISPATCHING'||ev.state==='DISPATCHED'))m.ae=Math.max(0,m.ae-1);ev.state='COMPLETED';ev.completed=Date.now();ev.updated=Date.now();ev.error=a.error||null;await this.s.put('e:'+ev.key,ev);await this.PM(m);await this.A();return J({ok:true})}
 async js(a){let ev=await this.s.get('e:'+a.event_key),m=await this.M();if(!ev||m.owner!==a.owner||m.epoch!==Number(a.epoch)||ev.owner!==a.owner||ev.epoch!==Number(a.epoch))return J({ok:false,error:'stale_fence'},409);let k='j:'+a.job_id,jb=await this.s.get(k);if(jb&&(jb.state==='RUNNING'||jb.state==='COMPLETED'))return J({ok:true,deduped:true});jb={id:a.job_id,event:a.event_key,owner:a.owner,epoch:Number(a.epoch),lane:a.lane||'bg',state:'RUNNING',started:Date.now(),lease:Date.now()+JOB_LEASE};await this.s.put(k,jb);m.aj++;await this.PM(m);await this.A(jb.lease);return J({ok:true})}
 async jd(a){let k='j:'+a.job_id,jb=await this.s.get(k);if(!jb)return J({ok:false,error:'unknown'},404);let m=await this.M();if(jb.state==='RUNNING')m.aj=Math.max(0,m.aj-1);jb.state='COMPLETED';jb.completed=Date.now();jb.error=a.error||null;await this.s.put(k,jb);await this.PM(m);return J({ok:true})}
 async force(a){if(this.e.QUALIFICATION_MODE!=='1')return J({ok:false,error:'disabled'},403);let o=String(a.owner||'');if(o!=='RAILWAY'&&o!=='RENDER')return J({ok:false,error:'owner'},400);let m=await this.M();if(m.owner!==o){m.epoch++;m.owner=o;m.ownerSince=Date.now();m.minUntil=Date.now();m.lastSwitch={to:o,at:Date.now(),reason:'qualification'};m.pf=0;m.hs=0;await this.PM(m)}return J({ok:true,owner:m.owner,epoch:m.epoch})}
 async D(ev){let m=await this.M(),n=Date.now();if(ev.state==='COMPLETED')return;if(ev.state==='DISPATCHED'&&ev.lease>n)return;if(ev.state==='DISPATCHED'){m.ae=Math.max(0,m.ae-1);ev.state='RETRYABLE'}if(ev.state!=='RECEIVED'&&ev.state!=='RETRYABLE')return;ev.owner=m.owner;ev.epoch=m.epoch;ev.attempts++;ev.state='DISPATCHING';ev.lease=n+EV_LEASE;ev.updated=n;m.ae++;await this.s.put('e:'+ev.key,ev);await this.PM(m);let er=null;try{let r=await BF(this.e,ev,m.owner,m.epoch,m.owner==='RENDER'?110000:20000);if(!r.ok)throw Error('http_'+r.status)}catch(z){er=ERR(z)}let q=await this.s.get('e:'+ev.key);m=await this.M();if(q&&q.state==='COMPLETED')return;if(!er){q.state='DISPATCHED';q.lease=Date.now()+EV_LEASE;q.updated=Date.now();q.error=null;if(q.owner==='RAILWAY'){m.pf=0;m.pfSince=0}else m.rf=0;await this.s.put('e:'+q.key,q);await this.PM(m);await this.A(q.lease);return}m.ae=Math.max(0,m.ae-1);q.state='RETRYABLE';q.error=er;q.next=Date.now()+Math.min(20000,1500*q.attempts);if(q.owner==='RAILWAY'&&m.owner==='RAILWAY'&&q.epoch===m.epoch){m.pf++;if(!m.pfSince)m.pfSince=Date.now();if(m.pf>=3&&Date.now()-m.pfSince>=20000&&Date.now()>=m.minUntil){m.epoch++;m.owner='RENDER';m.ownerSince=Date.now();m.minUntil=Date.now()+DWELL;m.fo++;m.lastSwitch={to:'RENDER',at:Date.now(),reason:'qualified_primary_failure'};m.hs=0;m.hsSince=0;q.next=Date.now()+1000}}else if(q.owner==='RENDER')m.rf++;m.lastError=er;await this.s.put('e:'+q.key,q);await this.PM(m);await this.A(q.next)}
 async probe(){let m=await this.M();if(m.owner!=='RENDER'||Date.now()<m.minUntil)return;if(m.ae||m.aj){m.hs=0;m.hsSince=0;await this.PM(m);return}let ok=false;try{let r=await fetch(this.e.RAILWAY_BASE_URL.replace(/\/+$/,'')+'/porfirchik/health',{signal:AbortSignal.timeout(3500)}),x=await r.json();ok=r.ok&&x.phase==='ready'}catch{}if(ok){if(!m.hsSince)m.hsSince=Date.now();m.hs++}else{m.hs=0;m.hsSince=0}if(m.hs>=3&&Date.now()-m.hsSince>=30000&&!m.ae&&!m.aj){m.epoch++;m.owner='RAILWAY';m.ownerSince=Date.now();m.minUntil=Date.now()+DWELL;m.fb++;m.lastSwitch={to:'RAILWAY',at:Date.now(),reason:'qualified_primary_recovery'};m.pf=0;m.pfSince=0;m.hs=0;m.hsSince=0}await this.PM(m)}
 async retryOut(){for(let [k,r] of await this.s.list({prefix:'o:',limit:100})){if(r.state!=='PENDING'||r.next>Date.now())continue;let m=await this.M(),ev=await this.s.get('e:'+r.event);if(!ev||m.owner!==r.owner||m.epoch!==r.epoch||ev.owner!==r.owner||ev.epoch!==r.epoch){r.state='FENCED';r.fenced=Date.now();await this.s.put(k,r);continue}try{r.vk=await VK(this.e,'messages.send',{peer_id:r.peer,random_id:r.random,message:r.message});r.state='SENT';r.sent=Date.now();r.error=null;await this.s.put(k,r)}catch(z){r.tries++;r.error=ERR(z);r.next=Date.now()+Math.min(120000,3000*r.tries);await this.s.put(k,r);await this.A(r.next)}}}
 async expire(){let m=await this.M();for(let [k,x] of await this.s.list({prefix:'j:',limit:200})){if(x.state==='RUNNING'&&x.lease<=Date.now()){x.state='EXPIRED';x.completed=Date.now();m.aj=Math.max(0,m.aj-1);await this.s.put(k,x)}if(x.completed&&Date.now()-x.completed>TTL)await this.s.delete(k)}await this.PM(m)}
 async alarm(){try{await this.expire();for(let [,e] of await this.s.list({prefix:'e:',limit:200})){if(e.state==='DISPATCHED'&&e.lease<=Date.now()||((e.state==='RECEIVED'||e.state==='RETRYABLE')&&e.next<=Date.now()))await this.D(e)}await this.probe();await this.retryOut();for(let [k,e] of await this.s.list({prefix:'e:',limit:500}))if(e.state==='COMPLETED'&&Date.now()-e.completed>TTL)await this.s.delete(k)}catch(z){let m=await this.M();m.lastError='alarm:'+ERR(z);await this.PM(m)}let m=await this.M(),n=Date.now()+60000;for(let [,e] of await this.s.list({prefix:'e:',limit:200})){if(e.state==='DISPATCHED')n=Math.min(n,e.lease);if(e.state==='RECEIVED'||e.state==='RETRYABLE')n=Math.min(n,e.next)}if(m.owner==='RENDER')n=Math.min(n,Date.now()+15000);if(m.aj)n=Math.min(n,Date.now()+30000);await this.s.setAlarm(Math.max(Date.now()+1000,n))}
 async diag(){let m=await this.M(),ec={},jc={},oc={};for(let [,x] of await this.s.list({prefix:'e:',limit:500}))ec[x.state]=(ec[x.state]||0)+1;for(let [,x] of await this.s.list({prefix:'j:',limit:500}))jc[x.state]=(jc[x.state]||0)+1;for(let [,x] of await this.s.list({prefix:'o:',limit:500}))oc[x.state]=(oc[x.state]||0)+1;return {ok:true,version:V,owner:m.owner,epoch:m.epoch,active_events:m.ae,active_jobs:m.aj,primary_failures:m.pf,primary_health_streak:m.hs,failovers:m.fo,failbacks:m.fb,last_switch:m.lastSwitch,last_error:m.lastError,event_counts:ec,job_counts:jc,output_counts:oc,free_only:true,ingress:'single-cloudflare',render_cold:true}}
}
async function IF(r,e,p){let b=await r.text(),a=await AUTH(r,e,b);if(!a)return J({ok:false,error:'auth'},401);let s=e.ARBITER.get(e.ARBITER.idFromName('PORFIRCHIK'));return s.fetch('https://do'+p,{method:'POST',headers:{'content-type':'application/json'},body:b})}
export default{async fetch(r,e,c){let u=new URL(r.url),s=e.ARBITER.get(e.ARBITER.idFromName('PORFIRCHIK'));if(u.pathname==='/healthz')return J({ok:true,version:V,free_only:true});if(u.pathname==='/diagnostic')return s.fetch('https://do/diag');if(u.pathname==='/internal/outbound')return IF(r,e,'/out');if(u.pathname==='/internal/complete')return IF(r,e,'/done');if(u.pathname==='/internal/job-start')return IF(r,e,'/js');if(u.pathname==='/internal/job-complete')return IF(r,e,'/jd');if(u.pathname==='/internal/force-owner')return e.QUALIFICATION_MODE==='1'?IF(r,e,'/force'):J({ok:false,error:'disabled'},403);if(u.pathname!==await CP(e.VK_GROUP_TOKEN))return J({ok:false,error:'not_found'},404);if(r.method!=='POST')return new Response('',{status:405});let raw=await r.text(),b;try{b=JSON.parse(raw)}catch{return T('bad request',400)}if(Number(b.group_id||0)!==GID)return T('forbidden',403);if(b.type==='confirmation'){try{let x=await VK(e,'groups.getCallbackConfirmationCode',{group_id:GID});return T(typeof x==='object'?x.code:x)}catch{return T('error',500)}}if(b.type!=='message_new')return T('ok');let k=await KEY(b),a=await s.fetch('https://do/in',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:k,raw,origin:u.origin})});return a.ok?T('ok'):T('error',500)}};
