import {
  LIGHT as L, DARK as K, otherPlayer, usesStack2, usesLadder
} from './ai/constants.js';
import {
  createInitialPosition, clonePosition, topPiece, isLegalMove, getLegalMoves, applyMove
} from './ai/rules.js';
import { chooseMove } from './ai/engine.js';
import { PERSONAS, selectPersonaAtGameStart } from './ai/personas.js';

'use strict';
var rule='C',mode='solo',difficulty='medium',styleChoice='mixed',aiPersona='architect',lastPersona='',human=L,computer=K,state,sel=null,gameNo=1,gameSeed=1,aiBusy=false;
var history=[],gameFirst=L;
function empty(first){return createInitialPosition(first||L);}
function clone(s){return clonePosition(s);}
function other(p){return otherPlayer(p);}
function top(s,c){return topPiece(s,c);}
function has(a,x){return a.indexOf(x)>=0;}
function useStack2(){return usesStack2(rule);}
function useLadder(){return usesLadder(rule);}
function probeTurn(s,p){if(s.turn===p)return s;var n=clonePosition(s);n.turn=p;return n;}
function legal(s,p,r,c){return isLegalMove(probeTurn(s,p),{player:p,rank:r,cell:c},rule);}
function moves(s,p){return getLegalMoves(probeTurn(s,p),p,rule).map(function(m){return{p:m.player,r:m.rank,c:m.cell};});}
function apply(s,m){return applyMove(probeTurn(s,m.p),{player:m.p,rank:m.r,cell:m.c},rule);}
function choosePersona(){aiPersona=selectPersonaAtGameStart(styleChoice,lastPersona,Math.random);lastPersona=aiPersona;}
function personaName(){return (PERSONAS[aiPersona]||PERSONAS.architect).name;}
function name(p){return p===L?'СВЕТЛЫЕ':'ТЁМНЫЕ';}function el(id){return document.getElementById(id);}function msg(x){el('msg').textContent=x;}function openM(id){el(id).className='modal open';}function closeM(id){el(id).className='modal';}function markSelected(attr,val){var a=document.querySelectorAll('[data-'+attr+']');for(var i=0;i<a.length;i++)a[i].classList.toggle('selected',a[i].getAttribute('data-'+attr)===val);}function updateSettingsUI(){var rn=rule==='C'?'СТЕК 2':rule==='D'?'ЛЕСТНИЦА':'СТЕК 2 + ЛЕСТНИЦА',mn=mode==='solo'?'ПРОТИВ ИИ':'2 ИГРОКА',dn=difficulty==='easy'?'ЛЁГКИЙ':difficulty==='hard'?'СЛОЖНЫЙ':'СРЕДНИЙ',sn=styleChoice==='mixed'?'СМЕШАННАЯ':styleChoice==='architect'?'АРХИТЕКТОР':styleChoice==='hunter'?'ОХОТНИК':styleChoice==='sentinel'?'СТРАЖ':'ЛОВКАЧ';el('statusRule').innerHTML='<strong>'+rule+'</strong> · '+rn;el('statusMode').innerHTML='<strong>РЕЖИМ</strong> · '+mn;el('statusLevel').innerHTML='<strong>ИИ</strong> · '+dn;el('statusStyle').innerHTML='<strong>СТРАТЕГИЯ</strong> · '+sn;el('statusLevel').style.display=mode==='solo'?'inline-block':'none';el('statusStyle').style.display=mode==='solo'?'inline-block':'none';markSelected('rule',rule);markSelected('mode',mode);markSelected('level',difficulty);markSelected('style',styleChoice);}
function start(first){gameFirst=first||L;state=empty(gameFirst);history=[];sel=null;aiBusy=false;gameSeed=((Date.now()^(gameNo*2654435761))>>>0)||1;choosePersona();render();if(mode==='solo'&&state.turn===computer)setTimeout(aiTurn,180);}function resetSession(){gameNo=1;start(L);}function select(r){if(state.status!=='playing'||aiBusy||(mode==='solo'&&state.turn===computer)||!has(state.remaining[state.turn],r))return;sel=(sel===r?null:r);render();}
function play(c){if(state.status!=='playing'||aiBusy)return;if(sel===null){if(state.board[c].length){var a=state.board[c],s='Клетка '+(c+1)+': ';for(var i=a.length-1;i>=0;i--)s+=name(a[i].player)+' '+a[i].rank+(i?' → ':'');msg(s);}return;}if(!legal(state,state.turn,sel,c))return;var m={p:state.turn,r:sel,c:c};history.push(m);state=apply(state,m,false);sel=null;render();if(mode==='solo'&&state.status==='playing'&&state.turn===computer){aiBusy=true;msg('Компьютер думает…');setTimeout(aiTurn,120);}}
function aiTurn(){if(mode!=='solo'||state.status!=='playing'||state.turn!==computer){aiBusy=false;return;}var result=chooseMove(state,{rule:rule,difficulty:difficulty,persona:aiPersona,seed:(gameSeed+state.moves*2246822519)>>>0});var move=result&&result.move?{p:result.move.player,r:result.move.rank,c:result.move.cell}:null;if(move){history.push(move);state=apply(state,move,false);}aiBusy=false;render();}
function shapeSize(r){return{w:22+r*5,h:18+r*4};}function pieceNode(p,r){var d=document.createElement('div'),z=shapeSize(r);d.className='bp '+p;d.style.width=z.w+'px';d.style.height=z.h+'px';d.textContent=r;return d;}
function renderRes(p,id){var box=el(id),r,b,z;box.innerHTML='';for(r=1;r<=9;r++){b=document.createElement('button');b.className='pieceBtn '+p+(sel===r&&state.turn===p?' sel':'');b.disabled=!has(state.remaining[p],r)||state.status!=='playing'||(mode==='solo'&&p===computer)||state.turn!==p||aiBusy;b.innerHTML='<span>'+r+'</span><i class="shape"></i>';z=shapeSize(r);b.querySelector('.shape').style.width=Math.min(30,z.w*.42)+'px';b.querySelector('.shape').style.height=Math.min(24,z.h*.35)+'px';(function(rr){b.onclick=function(){select(rr);};})(r);box.appendChild(b);}}
function fitBoard(){var app=document.querySelector('.app'),board=el('board');if(!app||!board)return;var kids=Array.prototype.slice.call(app.children),used=0;for(var i=0;i<kids.length;i++){var n=kids[i];if(n===board)continue;var st=getComputedStyle(n);used+=n.offsetHeight+(parseFloat(st.marginTop)||0)+(parseFloat(st.marginBottom)||0);}var ast=getComputedStyle(app),gap=parseFloat(ast.rowGap||ast.gap||0)||0;used+=gap*(kids.length-1)+(parseFloat(ast.paddingTop)||0)+(parseFloat(ast.paddingBottom)||0)+12;var maxW=Math.min(app.clientWidth-2,window.innerWidth-18,540);var maxH=Math.min(window.innerHeight-used,window.innerHeight*0.60);var size=Math.min(maxW,maxH);if(size<220)size=220;board.style.width=size+'px';board.style.height=size+'px';}
function render(){el('game').textContent='ПАРТИЯ '+gameNo+' · '+rule;el('turn').textContent=state.status==='playing'?'ХОД: '+name(state.turn):(state.status==='draw'?'НИЧЬЯ':'ПОБЕДА');el('level').style.display=mode==='solo'?'inline-block':'none';el('level').textContent='ИИ';updateSettingsUI();el('dn').className=state.turn===K?'activeName':'';el('ln').className=state.turn===L?'activeName':'';el('dh').textContent=mode==='solo'?'КОМПЬЮТЕР · '+personaName():'';el('lh').textContent=mode==='solo'?'ВЫ':'';renderRes(K,'darkRes');renderRes(L,'lightRes');var b=el('board');b.innerHTML='';for(var c=0;c<9;c++){var e=document.createElement('button');e.className='cell';if(sel!==null&&legal(state,state.turn,sel,c))e.className+=' legal';if(state.winLine&&state.winLine.indexOf(c)>=0)e.className+=' win';var t=top(state,c);if(t)e.appendChild(pieceNode(t.player,t.rank));if(state.board[c].length>1){var d=document.createElement('span');d.className='depth';d.textContent='×'+state.board[c].length;e.appendChild(d);}(function(cc){e.onclick=function(){play(cc);};})(c);b.appendChild(e);}el('undo').disabled=!history.length||aiBusy;if(state.status==='playing'){el('end').className='end';if(!aiBusy)msg((mode==='solo'&&state.turn===computer)?'Ход компьютера.':name(state.turn)+': выберите размер.');}else{el('end').className='end open';el('endTitle').textContent=state.status==='draw'?'НИЧЬЯ':name(state.turn)+' ПОБЕДИЛИ';el('endInfo').textContent=state.moves+' ходов';msg('Партия завершена.');}fitBoard();}
function undo(){if(!history.length||aiBusy)return;var h=history.slice(),n=1;if(mode==='solo'&&h.length>=2&&h[h.length-1].p===computer)n=2;h=h.slice(0,-n);var s=empty(gameFirst),i;history=[];for(i=0;i<h.length;i++){var next=apply(s,h[i],false);if(!next)break;s=next;history.push(h[i]);}state=s;sel=null;render();}
el('rules').onclick=function(){openM('rulesM');};el('mode').onclick=function(){openM('modeM');};el('level').onclick=function(){if(mode==='solo')openM('levelM');};el('help').onclick=function(){openM('helpM');};el('undo').onclick=undo;el('reset').onclick=function(){if(confirm('Сбросить текущую партию?'))start(L);};el('next').onclick=function(){gameNo++;start(gameNo%2?L:K);};
var cs=document.querySelectorAll('[data-close]');for(var i=0;i<cs.length;i++)cs[i].onclick=function(){closeM(this.getAttribute('data-close'));};var rs=document.querySelectorAll('[data-rule]');for(i=0;i<rs.length;i++)rs[i].onclick=function(){rule=this.getAttribute('data-rule');closeM('rulesM');resetSession();};var ms=document.querySelectorAll('[data-mode]');for(i=0;i<ms.length;i++)ms[i].onclick=function(){mode=this.getAttribute('data-mode');closeM('modeM');resetSession();};var ls=document.querySelectorAll('[data-level]');for(i=0;i<ls.length;i++)ls[i].onclick=function(){difficulty=this.getAttribute('data-level');closeM('levelM');resetSession();};var ss=document.querySelectorAll('[data-style]');for(i=0;i<ss.length;i++)ss[i].onclick=function(){styleChoice=this.getAttribute('data-style');closeM('levelM');resetSession();};
start(L);window.addEventListener('resize',fitBoard);setTimeout(fitBoard,0);
