import {
  LIGHT as L, DARK as K, LINES, otherPlayer, usesStack2, usesLadder
} from './ai/constants.js';
import {
  createInitialPosition, clonePosition, topPiece, isLegalMove, getLegalMoves, applyMove
} from './ai/rules.js';

'use strict';
var rule='C',mode='solo',difficulty='medium',styleChoice='mixed',aiPersona='architect',lastPersona='',human=L,computer=K,state,sel=null,gameNo=1,aiBusy=false,LADDER_TRIPLES=[],PERSONAS={architect:{name:'АРХИТЕКТОР',attack:1.12,defense:1.02,cover:.75,flex:1.65,fork:1.30,resource:1.05,chaos:.08},hunter:{name:'ОХОТНИК',attack:1.48,defense:.82,cover:1.65,flex:.82,fork:1.12,resource:.55,chaos:.14},sentinel:{name:'СТРАЖ',attack:.92,defense:1.55,cover:.72,flex:1.10,fork:.92,resource:1.55,chaos:.05},trickster:{name:'ЛОВКАЧ',attack:1.10,defense:.98,cover:1.00,flex:1.12,fork:1.70,resource:.78,chaos:.26}};for(var la=1;la<=9;la++)for(var lb=1;lb<=9;lb++)for(var lc=1;lc<=9;lc++)if((la<lb&&lb<lc)||(la>lb&&lb>lc))LADDER_TRIPLES.push([la,lb,lc]);
var history=[],gameFirst=L;
function empty(first){return createInitialPosition(first||L);}
function clone(s){return clonePosition(s);}
function other(p){return otherPlayer(p);}
function top(s,c){return topPiece(s,c);}
function has(a,x){return a.indexOf(x)>=0;}
function useStack2(){return usesStack2(rule);}
function useLadder(){return usesLadder(rule);}
function probeTurn(s,p){if(s.turn===p)return s;var n=clonePosition(s);n.turn=p;return n;}
function legal(s,p,r,c){return isLegalMove(probeTurn(s,p),{player:p,rank:r,cell:c},rule);}
function moves(s,p){return getLegalMoves(probeTurn(s,p),p,rule).map(function(m){return{p:m.player,r:m.rank,c:m.cell};});}
function apply(s,m){return applyMove(probeTurn(s,m.p),{player:m.p,rank:m.r,cell:m.c},rule);}
function immediateWins(s,p){var ms=moves(s,p),n=0,i,x;for(i=0;i<ms.length;i++){x=apply(s,ms[i],false);if(x&&x.status==='win'&&x.turn===p)n++;}return n;}
function choosePersona(){var keys=['architect','hunter','sentinel','trickster'],pick;if(styleChoice!=='mixed'){aiPersona=styleChoice;return;}do{pick=keys[Math.floor(Math.random()*keys.length)];}while(keys.length>1&&pick===lastPersona);aiPersona=pick;lastPersona=pick;}
function persona(){return PERSONAS[aiPersona]||PERSONAS.architect;}
function lockedValue(s,p){if(!useStack2())return 0;var v=0,c,t;for(c=0;c<9;c++)if(s.board[c].length===2){t=top(s,c);v+=(t.player===p?1:-1)*(c===4?7:(c%2===0?5:4));}return v;}
function hasBigger(s,p,r){for(var i=0;i<s.remaining[p].length;i++)if(s.remaining[p][i]>r)return true;return false;}
function centerFlex(r){return 2*(r-1)*(9-r);}
function ladderLineScore(s,p,a){var known=[0,0,0],need=[0,0,0],own=0,covers=0,j,t,c,blocked=false;for(j=0;j<3;j++){c=a[j];t=top(s,c);if(!t){need[j]=-1;continue;}if(t.player===p){known[j]=t.rank;own++;}else{if((useStack2()&&s.board[c].length>=2)||!hasBigger(s,p,t.rank)){blocked=true;break;}need[j]=t.rank;covers++;}}if(blocked)return own?-20*own:-5;var count=0,i,tr,r,ok;for(i=0;i<LADDER_TRIPLES.length;i++){tr=LADDER_TRIPLES[i];ok=true;for(j=0;j<3;j++){r=tr[j];if(known[j]){if(r!==known[j]){ok=false;break;}}else{if(!has(s.remaining[p],r)){ok=false;break;}if(need[j]>0&&r<=need[j]){ok=false;break;}}}if(ok)count++;}if(!count)return own?-70*own:-9;return (own===2?34:own===1?8:1)+Math.min(16,count*.22)-covers*3;}
function attackPotential(s,p){var score=0,i,a,ours,opp,j,t;if(useLadder()){for(i=0;i<LINES.length;i++)score+=ladderLineScore(s,p,LINES[i]);return score;}for(i=0;i<LINES.length;i++){a=LINES[i];ours=0;opp=0;for(j=0;j<3;j++){t=top(s,a[j]);if(t){if(t.player===p)ours++;else opp++;}}if(!opp)score+=ours===2?20:ours===1?5:1;}return score;}
function resourceValue(s,p){var a=s.remaining[p],sum=0,i;for(i=0;i<a.length;i++)sum+=a[i]*a[i];return sum;}
function boardValue(s,p){var sc=0,c,t,q;for(c=0;c<9;c++){t=top(s,c);if(!t)continue;q=(c===4?6:(c%2===0?4:3));if(useLadder()&&c===4)q=2+centerFlex(t.rank)*.22;sc+=(t.player===p?q:-q);}return sc;}
function evaluate(s,p){if(s.status==='win')return s.turn===p?100000:-100000;if(s.status==='draw')return 0;var P=persona(),op=other(p),atk=attackPotential(s,p),def=attackPotential(s,op),sc=boardValue(s,p);sc+=atk*P.attack-def*P.defense;sc+=lockedValue(s,p)*3.4;sc+=(resourceValue(s,p)-resourceValue(s,op))*.018*P.resource;return sc;}
function quickMoveScore(s,m,p){var P=persona(),before=top(s,m.c),n=apply(s,m,false),v;if(!n)return-1e9;if(n.status==='win'&&n.turn===p)return 1e9;if(useLadder()&&m.c===4&&centerFlex(m.r)===0)return-1e9;v=evaluate(n,p);if(useLadder()&&m.c===4)v+=centerFlex(m.r)*.85*P.flex;else if(m.c===4)v+=5;else if(m.c%2===0)v+=2.5;if(before)v+=(useStack2()?18:7)*P.cover;v-=m.r*.22*P.resource;return v;}
function rootMoveScore(s,m,p){var P=persona(),n=apply(s,m,false),v=quickMoveScore(s,m,p),threats,danger;if(!n)return-1e9;if(v>=1e8)return v;threats=immediateWins(n,p);danger=immediateWins(n,other(p));v+=threats*24*P.fork-danger*35000;if(useLadder()&&m.c===4)v+=centerFlex(m.r)*1.15*P.flex;return v;}
function ordered(s,p,lim,root){var a=moves(s,p),i;for(i=0;i<a.length;i++)a[i].v=root?rootMoveScore(s,a[i],p):quickMoveScore(s,a[i],p);a.sort(function(x,y){return y.v-x.v;});if(lim&&a.length>lim)a=a.slice(0,lim);return a;}
function stateKey(s,d){var z=[s.turn,d],c,t;for(c=0;c<9;c++){t=top(s,c);z.push(t?t.player.charAt(0)+t.rank:'-');z.push(s.board[c].length);}z.push(s.remaining.light.join(''));z.push(s.remaining.dark.join(''));return z.join('|');}
function search(s,root,depth,alpha,beta,branch,cache){if(depth<=0||s.status!=='playing')return evaluate(s,root);var key=stateKey(s,depth),hit=cache[key];if(hit!==undefined)return hit;var p=s.turn,ms=ordered(s,p,branch,false),best=(p===root?-1e12:1e12),i,n,v;if(!ms.length)return evaluate(s,root);for(i=0;i<ms.length;i++){n=apply(s,ms[i],false);v=search(n,root,depth-1,alpha,beta,branch,cache);if(p===root){if(v>best)best=v;if(best>alpha)alpha=best;}else{if(v<best)best=v;if(best<beta)beta=best;}if(beta<=alpha)break;}cache[key]=best;return best;}
function weightedPick(scored,band,chaos){var best=scored[0].score,eligible=[],i,m,w,total=0,r;for(i=0;i<scored.length;i++){if(scored[i].score<best-band)break;m=scored[i];w=Math.exp((m.score-best)/Math.max(1,band*(.32+chaos)));eligible.push({m:m.move,w:w});total+=w;}r=Math.random()*total;for(i=0;i<eligible.length;i++){r-=eligible[i].w;if(r<=0)return eligible[i].m;}return eligible[0].m;}
function aiPick(s,p){var P=persona(),all=moves(s,p),i,n,ms,pool,depth,rootLim,branch,cache={},scored=[],safe=[],v;if(!all.length)return null;
for(i=0;i<all.length;i++){n=apply(s,all[i],false);if(n&&n.status==='win'&&n.turn===p)return all[i];}
for(i=0;i<all.length;i++){n=apply(s,all[i],false);if(n&&immediateWins(n,other(p))===0)safe.push(all[i]);}
if(safe.length)all=safe;
if(difficulty==='easy'){ms=all;for(i=0;i<ms.length;i++)ms[i].v=rootMoveScore(s,ms[i],p);ms.sort(function(a,b){return b.v-a.v;});pool=ms.slice(0,Math.max(4,Math.ceil(ms.length*.38)));return pool[Math.floor(Math.random()*pool.length)];}
if(difficulty==='hard'){rootLim=22;branch=11;depth=all.length<20?4:(all.length<44?3:2);}else{rootLim=16;branch=9;depth=2;}
ms=all;for(i=0;i<ms.length;i++)ms[i].v=rootMoveScore(s,ms[i],p);ms.sort(function(a,b){return b.v-a.v;});if(ms.length>rootLim)ms=ms.slice(0,rootLim);
for(i=0;i<ms.length;i++){n=apply(s,ms[i],false);v=search(n,p,depth,-1e12,1e12,branch,cache);v+=ms[i].v*.18;scored.push({move:ms[i],score:v});}
scored.sort(function(a,b){return b.score-a.score;});if(!scored.length)return ms[0];if(difficulty==='hard')return weightedPick(scored,7+P.chaos*10,P.chaos);return weightedPick(scored,18+P.chaos*18,.20+P.chaos);}
function name(p){return p===L?'СВЕТЛЫЕ':'ТЁМНЫЕ';}function el(id){return document.getElementById(id);}function msg(x){el('msg').textContent=x;}function openM(id){el(id).className='modal open';}function closeM(id){el(id).className='modal';}function markSelected(attr,val){var a=document.querySelectorAll('[data-'+attr+']');for(var i=0;i<a.length;i++)a[i].classList.toggle('selected',a[i].getAttribute('data-'+attr)===val);}function updateSettingsUI(){var rn=rule==='C'?'СТЕК 2':rule==='D'?'ЛЕСТНИЦА':'СТЕК 2 + ЛЕСТНИЦА',mn=mode==='solo'?'ПРОТИВ ИИ':'2 ИГРОКА',dn=difficulty==='easy'?'ЛЁГКИЙ':difficulty==='hard'?'СЛОЖНЫЙ':'СРЕДНИЙ',sn=styleChoice==='mixed'?'СМЕШАННАЯ':styleChoice==='architect'?'АРХИТЕКТОР':styleChoice==='hunter'?'ОХОТНИК':styleChoice==='sentinel'?'СТРАЖ':'ЛОВКАЧ';el('statusRule').innerHTML='<strong>'+rule+'</strong> · '+rn;el('statusMode').innerHTML='<strong>РЕЖИМ</strong> · '+mn;el('statusLevel').innerHTML='<strong>ИИ</strong> · '+dn;el('statusStyle').innerHTML='<strong>СТРАТЕГИЯ</strong> · '+sn;el('statusLevel').style.display=mode==='solo'?'inline-block':'none';el('statusStyle').style.display=mode==='solo'?'inline-block':'none';markSelected('rule',rule);markSelected('mode',mode);markSelected('level',difficulty);markSelected('style',styleChoice);}
function start(first){gameFirst=first||L;state=empty(gameFirst);history=[];sel=null;aiBusy=false;choosePersona();render();if(mode==='solo'&&state.turn===computer)setTimeout(aiTurn,180);}function resetSession(){gameNo=1;start(L);}function select(r){if(state.status!=='playing'||aiBusy||(mode==='solo'&&state.turn===computer)||!has(state.remaining[state.turn],r))return;sel=(sel===r?null:r);render();}
function play(c){if(state.status!=='playing'||aiBusy)return;if(sel===null){if(state.board[c].length){var a=state.board[c],s='Клетка '+(c+1)+': ';for(var i=a.length-1;i>=0;i--)s+=name(a[i].player)+' '+a[i].rank+(i?' → ':'');msg(s);}return;}if(!legal(state,state.turn,sel,c))return;var m={p:state.turn,r:sel,c:c};history.push(m);state=apply(state,m,false);sel=null;render();if(mode==='solo'&&state.status==='playing'&&state.turn===computer){aiBusy=true;msg('Компьютер думает…');setTimeout(aiTurn,120);}}
function aiTurn(){if(mode!=='solo'||state.status!=='playing'||state.turn!==computer){aiBusy=false;return;}var m=aiPick(state,computer);if(m){history.push(m);state=apply(state,m,false);}aiBusy=false;render();}
function shapeSize(r){return{w:22+r*5,h:18+r*4};}function pieceNode(p,r){var d=document.createElement('div'),z=shapeSize(r);d.className='bp '+p;d.style.width=z.w+'px';d.style.height=z.h+'px';d.textContent=r;return d;}
function renderRes(p,id){var box=el(id),r,b,z;box.innerHTML='';for(r=1;r<=9;r++){b=document.createElement('button');b.className='pieceBtn '+p+(sel===r&&state.turn===p?' sel':'');b.disabled=!has(state.remaining[p],r)||state.status!=='playing'||(mode==='solo'&&p===computer)||state.turn!==p||aiBusy;b.innerHTML='<span>'+r+'</span><i class="shape"></i>';z=shapeSize(r);b.querySelector('.shape').style.width=Math.min(30,z.w*.42)+'px';b.querySelector('.shape').style.height=Math.min(24,z.h*.35)+'px';(function(rr){b.onclick=function(){select(rr);};})(r);box.appendChild(b);}}
function fitBoard(){var app=document.querySelector('.app'),board=el('board');if(!app||!board)return;var kids=Array.prototype.slice.call(app.children),used=0;for(var i=0;i<kids.length;i++){var n=kids[i];if(n===board)continue;var st=getComputedStyle(n);used+=n.offsetHeight+(parseFloat(st.marginTop)||0)+(parseFloat(st.marginBottom)||0);}var ast=getComputedStyle(app),gap=parseFloat(ast.rowGap||ast.gap||0)||0;used+=gap*(kids.length-1)+(parseFloat(ast.paddingTop)||0)+(parseFloat(ast.paddingBottom)||0)+12;var maxW=Math.min(app.clientWidth-2,window.innerWidth-18,540);var maxH=Math.min(window.innerHeight-used,window.innerHeight*0.60);var size=Math.min(maxW,maxH);if(size<220)size=220;board.style.width=size+'px';board.style.height=size+'px';}
function render(){el('game').textContent='ПАРТИЯ '+gameNo+' · '+rule;el('turn').textContent=state.status==='playing'?'ХОД: '+name(state.turn):(state.status==='draw'?'НИЧЬЯ':'ПОБЕДА');el('level').style.display=mode==='solo'?'inline-block':'none';el('level').textContent='ИИ';updateSettingsUI();el('dn').className=state.turn===K?'activeName':'';el('ln').className=state.turn===L?'activeName':'';el('dh').textContent=mode==='solo'?'КОМПЬЮТЕР · '+persona().name:'';el('lh').textContent=mode==='solo'?'ВЫ':'';renderRes(K,'darkRes');renderRes(L,'lightRes');var b=el('board');b.innerHTML='';for(var c=0;c<9;c++){var e=document.createElement('button');e.className='cell';if(sel!==null&&legal(state,state.turn,sel,c))e.className+=' legal';if(state.winLine&&state.winLine.indexOf(c)>=0)e.className+=' win';var t=top(state,c);if(t)e.appendChild(pieceNode(t.player,t.rank));if(state.board[c].length>1){var d=document.createElement('span');d.className='depth';d.textContent='×'+state.board[c].length;e.appendChild(d);}(function(cc){e.onclick=function(){play(cc);};})(c);b.appendChild(e);}el('undo').disabled=!history.length||aiBusy;if(state.status==='playing'){el('end').className='end';if(!aiBusy)msg((mode==='solo'&&state.turn===computer)?'Ход компьютера.':name(state.turn)+': выберите размер.');}else{el('end').className='end open';el('endTitle').textContent=state.status==='draw'?'НИЧЬЯ':name(state.turn)+' ПОБЕДИЛИ';el('endInfo').textContent=state.moves+' ходов';msg('Партия завершена.');}fitBoard();}
function undo(){if(!history.length||aiBusy)return;var h=history.slice(),n=1;if(mode==='solo'&&h.length>=2&&h[h.length-1].p===computer)n=2;h=h.slice(0,-n);var s=empty(gameFirst),i;history=[];for(i=0;i<h.length;i++){var next=apply(s,h[i],false);if(!next)break;s=next;history.push(h[i]);}state=s;sel=null;render();}
el('rules').onclick=function(){openM('rulesM');};el('mode').onclick=function(){openM('modeM');};el('level').onclick=function(){if(mode==='solo')openM('levelM');};el('help').onclick=function(){openM('helpM');};el('undo').onclick=undo;el('reset').onclick=function(){if(confirm('Сбросить текущую партию?'))start(L);};el('next').onclick=function(){gameNo++;start(gameNo%2?L:K);};
var cs=document.querySelectorAll('[data-close]');for(var i=0;i<cs.length;i++)cs[i].onclick=function(){closeM(this.getAttribute('data-close'));};var rs=document.querySelectorAll('[data-rule]');for(i=0;i<rs.length;i++)rs[i].onclick=function(){rule=this.getAttribute('data-rule');closeM('rulesM');resetSession();};var ms=document.querySelectorAll('[data-mode]');for(i=0;i<ms.length;i++)ms[i].onclick=function(){mode=this.getAttribute('data-mode');closeM('modeM');resetSession();};var ls=document.querySelectorAll('[data-level]');for(i=0;i<ls.length;i++)ls[i].onclick=function(){difficulty=this.getAttribute('data-level');closeM('levelM');resetSession();};var ss=document.querySelectorAll('[data-style]');for(i=0;i<ss.length;i++)ss[i].onclick=function(){styleChoice=this.getAttribute('data-style');closeM('levelM');resetSession();};
start(L);window.addEventListener('resize',fitBoard);setTimeout(fitBoard,0);
